apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quakewatch-check
            image: mayam123/quakewatch:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Checking earthquake data at $(date)"
              curl -s http://quakewatch-service/health || echo "Health check failed"
          restartPolicy: OnFailure