apiVersion: v2
name: quakewatch
description: A Helm chart for QuakeWatch earthquake monitoring application
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - earthquake
  - monitoring
  - flask
maintainers:
  - name: MAYAMEIS
    email: maya.meis@gmail.com