apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
      - name: quakewatch
        image: mayam123/quakewatch:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: quakewatch-config
        - secretRef:
            name: quakewatch-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi