apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quakewatch-metrics
  namespace: default
  labels:
    app: quakewatch
spec:
  type: LoadBalancer
  selector:
    app: quakewatch
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000