apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quakewatch-metrics
  namespace: default
  labels:
    app: quakewatch
    release: prometheus
spec:
  selector:
    matchLabels:
      app: quakewatch
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
